### ISSUE TITLE
Unhandled Exception When Trying to Use Tool

### ISSUE THREAD

**Issue by zaffuto** [jaredhaight/PSAttackBuildTool#18]
### What were you doing when the error happened
After downloading the tool/unzipping it, I clicked on the tool and it pops up with a window about the tool and the default warning, etc. When I press the enter key to start the build process, I get an error that stops everything. (PSAttackToolBuild.exe has stopped working)

### What was the error message (exact text is good, screenshot is better)
Status: Searching Github
Unhandled Exception: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel. 
  at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
  at System.Net.WebClient.DownloadString(Uri address)
  at PSAttackBuildTool.Utils.PSABTUtils.GetPSAttack()
  at PSAttackBuildTool.Program.Main(String[] args)

### What Operating System did this happen on
Tried on both Windows 7 and Windows 10 (both fairly new installs with .Net 3.5 installed)

**Comment by Lyes06** [comment]
Same issue for me on Windows 7 ...

**Comment by fsacer** [comment]
To fix the issue change code to this in PSABTUtils.cs:77 :

` 
 public static string GetPSAttackBuildToolDir()
{
    string PSAttackBuildDir = "C:\\PSAttackBuildTool";
    if (!(Directory.Exists(PSAttackBuildDir)))
    {
        Directory.CreateDirectory(PSAttackBuildDir);
    }
    return PSAttackBuildDir+"\\";
}

public static Attack GetPSAttack()
{
    System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
    WebClient wc = new System.Net.WebClient();
    // This took a while to figure out: https://developer.github.com/v3/#user-agent-required
`

**Comment by Lyes06** [comment]
Thank you !
Ok now it works …
But I had to add  2 \

The code

public static string GetPSAttackBuildToolDir()
{
string PSAttackBuildDir = “C:\\PSAttackBuildTool";
if (!(Directory.Exists(PSAttackBuildDir)))
{
Directory.CreateDirectory(PSAttackBuildDir);
}
return PSAttackBuildDir+”\\";
}

public static Attack GetPSAttack()
{
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

WebClient wc = new System.Net.WebClient(); 


Now the zipball  is downloaded but I’v got a new error:


  __________________________________________________________
 /              __                                          \
 |    _____ ____\ \  _____ _____ _____ _____ _____ _____    |
 |   |  _  |   __\ \|  _  |_   _|_   _|  _  |     |  |  |   |
 |   |   __|__   |> |     | | |   | | |     |   --|    -|   |
 |   |__|  |_____/ /|__|__| |_|   |_| |__|__|_____|__|__|   |
 |              /_/                   BUILD TOOL v1.9       |
 \__________________________________________________________/

 Stage: Processing Modules
 Status: ERROR!!

 There was an error processing PowerSploit - Invoke-Mimikatz.



 Error message:

Impossible to load the file or assembly  'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31
bf3856ad364e35’ or a depency. No such the specified file.

 Press enter to continue building PS>Attack..

**Comment by jaredhaight** [comment]
@fsacer or @Lyes06 - Would one of you mind submitting a PR with the new line? It would be greatly appreciated.

@Lyes06 - Can you open a new issue for the System.Management.Automation error that you're getting?

Thanks!

**Comment by bantixgithub** [comment]
I have the same issue when executing PSAttackBuildTool.exe v1.9.1. I'm going to build it myself but i haven't archived any progress with that yet. 

Here is the whole output:

 Stage: Getting PS>Attack
 Status: Searching Github
Unhandled Exception: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at PSAttackBuildTool.Utils.PSABTUtils.GetPSAttack()
   at PSAttackBuildTool.Program.Main(String[] args)

**Comment by bantixgithub** [comment]
After some researching I found an answer to my problem:

I added the following lines to: public static Attack GetPSAttack() in: PSABTUtils.cs

ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            WebClient wc = new System.Net.WebClient();
            wc.Headers.Add("User-Agent: Other");
