### ISSUE TITLE
The specified path, file name, or both are too long

### ISSUE THREAD

**Issue by sdcampbell** [jaredhaight/PSAttackBuildTool#23]
### What were you doing when the error happened

I ran the build tool from the command line. Please note that I've already edited the registry to enable long file names, restarted, and still get the same error.

### What was the error message (exact text is good, screenshot is better)

  __________________________________________________________
 /              __                                          \
 |    _____ ____\ \  _____ _____ _____ _____ _____ _____    |
 |   |  _  |   __\ \|  _  |_   _|_   _|  _  |     |  |  |   |
 |   |   __|__   |> |     | | |   | | |     |   --|    -|   |
 |   |__|  |_____/ /|__|__| |_|   |_| |__|__|_____|__|__|   |
 |              /_/                   BUILD TOOL v1.9.1       |
 \__________________________________________________________/

 Stage: Getting PS>Attack
 Status: Found Version: v1.99.1
                                                                                                                         Unzipping to: C:\Users\scampbell\AppData\Roaming\PSAttackBuildTool\PSAttackSrc\
Unhandled Exception: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at PSAttackBuildTool.Utils.PSABTUtils.UnzipFile(String zipSource, String destinationDir)
   at PSAttackBuildTool.Program.Main(String[] args)
PS C:\PSABT>

### What Operating System did this happen on

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134

**Comment by ankushgoel27** [comment]
i am seeing the same exception...how do i fix it?
